services:
  - type: web
    name: frontend-with_rubber
    env: static
    buildCommand: cd ui; yarn install --production=false; yarn build
    staticPublishPath: ui/build/
    buildFilter:
      paths:
        - ui/**/*.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: backend-with_rubber
    plan: free
    env: node
    buildCommand: cd api; yarn; npx knex migrate:latest
    startCommand: cd api; yarn run prod
    buildFilter:
      paths:
        - api/**/*.js
databases:
  - name: database-with_rubber
    plan: free
    databaseName: with_rubber_dev
    ipAllowList: [] # only allow internal connections



