/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
 
 
  await knex('product').insert([
    {
      "id":38,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-gul-womens-response-32mm-flatlock-back-zip-wetsuit-re1319-navy-paisley-p-39931.html",
      "name": "Womens Response 3/2mm Flatlock Back Zip Wetsuit",
      "brand": "GUL",
      "sku": "RE1319-C1",
      "description": "The Gul Response range is the perfect combination of value for money and performance. Constructed using Flatlock seams and X-Flex super stretch panels for comfort with seam free seat construction. Featuring highly durable Powertex4 knees, meaning four way stretch for extra felability and ensuring an increased lifespan. The Response wetsuit perfectly equipts an al l round watersports enthusiast.",
      "price": "88.99 ",
      "sizes": "4,6,6T,8,8T,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Gul%20Womens%20Response%2032mm%20SDL%20FL%20Steamer%20RE1319-C1%20-%20Navy%20Paisley%20front.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":39,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-rip-curl-womens-dawn-patrol-32mm-back-zip-wetsuit-wsm9rw-black-p-37968.html",
      "name": "Womens Dawn Patrol 3/2mm Back Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9RW",
      "description": "The Rip Curl Dawn Patrol Warmth is a brand new addition the range for this season, featuring a full flash dry lining internally to the front of the suit, which provides incredible warmth during those colder sessions! Truly the ultimate all-around wetsuit combining the features of a top end suit at an economical price. Whether you're getting into surfing or out there every weekend, this suit has you covered with its E5 neoprene and E5 Flash Lining, plus the entire suit is glued and blindstitched with seam taping for strength.  Warmth, stretch and flexibility at a great price.",
      "price": "259.95 ",
      "sizes": "4,6,8,8T,10,10T,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Rip-Curl-Womens-Dawn-Patrol-Back-Zip-Wetsuit-WSM9RW---Black.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":40,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2020-rip-curl-womens-omega-32mm-back-zip-gbs-wetsuit-wsm4lw-slate-p-34176.html",
      "name": "Womens Omega 3/2mm Back Zip GBS Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM4LW",
      "description": "A quality wetsuit at an economical price, The omega is the foundation of Rip Curl's innovative Wetsuit range. Boasting some of the best neoprene with Ultralite and FreeFlex and a back zip entry, a simple and affordable solution to your wetsuit needs.",
      "price": "125.99 ",
      "sizes": "14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Rip-Curl-Womens-Omega-Back-Zip-GBS-Wetsuit-WSM4LW-Black-Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":41,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-rip-curl-womens-dawn-patrol-warmth-32mm-chest-zip-wetsuit-wsm9ow-charcoal-p-38714.html",
      "name": "Womens Dawn Patrol Warmth 3/2mm Chest Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9OW",
      "description": "The Rip Curl Dawn Patrol Warmth is a brand new addition the range for this season, featuring a full flash dry lining internally to the front of the suit, which provides incredible warmth during those colder sessions! Truly the ultimate all-around wetsuit combining the features of a top end suit at an economical price. Whether you're getting into surfing or out there every weekend, this suit has you covered with its E5 neoprene and E5 Flash Lining, plus the entire suit is glued and blindstitched with seam taping for strength.  Warmth, stretch and flexibility at a great price.",
      "price": "259.99 ",
      "sizes": "8,10,12",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2021%20Rip%20Curl%20Womens%20Dawn%20Patrol%2053mm%20Chest%20Zip%20Wetsuit%20WSM9MW%20-%20Charcoal.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":42,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-rip-curl-womens-dawn-patrol-32mm-back-zip-wetsuit-wsm9ns-peach-p-43828.html",
      "name": "Womens Dawn Patrol 3/2mm Back Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9NS",
      "description": "The Dawn Patrol offers performance and warmth features along with durability and great value. This wetsuit has many of the high-end features you will find in our Ultimate suits including E5 Flash Lining, E5 neoprene, E4 Thermo lining.",
      "price": "259.95 ",
      "sizes": "4,6,8,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2023%20Rip%20Curl%20Womens%20Dawn%20Patrol%2032mm%20Back%20Zip%20Wetsuit%20WSM9NS%20%20Peach%20Main%202.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":43,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-rip-curl-womens-flashbomb-32mm-chest-zip-wetsuit-wstyes-washed-black-p-41050.html",
      "name": "Womens Flashbomb 3/2mm Chest Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSTYES",
      "description": "The Women's Flashbomb 3/2 Chest Zip Fullsuit now comes with E6 Flash Lining that provides 20% more stretch, warmth and quick dry tech. Seams are also taped with E6 Flash Lining tape for extra comfort and water seam sealing. Mesh skin panels absorb solar rays and reduce wind chill for longer sessions.",
      "price": "359.99 ",
      "sizes": "8,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/41050-1.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":44,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-skins-womens-element-32mm-back-zip-wetsuit-el32stw-bluestone-lilac-black-p-44267.html",
      "name": "Womens Element 3/2mm Back Zip Wetsuit",
      "brand": "C-Skins",
      "sku": "C-EL32STW",
      "description": "The Element series is all about combining performance technology with unbeatable value. We utilise our exclusive Xtend neoprene in the shoulder and sleeves for excellent flexibility, a Super Seal Glideskin collar for exceptional comfort and Dura Flex knee pads for unbeatable durability. The Element is the best wetsuit on the market for those discovering the sea.",
      "price": "107.88 ",
      "sizes": "2,4,6S,6,8S,8,10,14S,12,16S,14,16",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2023%20C-Skins%20Womens%20Element%2032mm%20Back%20Zip%20Wetsuit%20C-EL32STW%20-%20Bluestone%20%20Lilac%20Black%20-%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":45,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-jobe-womens-sofia-32mm-back-zip-wetsuit-303522001-midnight-blue-p-41280.html",
      "name": "Womens Sofia 3/2mm Back Zip Wetsuit",
      "brand": "JOBE",
      "sku": "303522001",
      "description": "The Sofia has been designed with comfy full stretch neoprene to provide its user with all the freedom of movement necessary. Next to the fact that Sofia has a feminine cut and its eye-catching print make you look great, it makes you feel even greater due to extra effort coming with a comfortable stitch construction, which feels ultra-soft on your skin. The added ultra-resistant and ultra-high endurance kneepads protect against abrasion.",
      "price": "94.68 ",
      "sizes": "M,XL",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/303522001-zoom.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":46,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-rip-curl-womens-dawn-patrol-32mm-chest-zip-wetsuit-wsm9ow-black-p-39120.html",
      "name": "Womens Dawn Patrol 3/2mm Chest Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9OW",
      "description": "The Rip Curl Dawn Patrol Warmth is a brand new addition the range for this season, featuring a full flash dry lining internally to the front of the suit, which provides incredible warmth during those colder sessions! Truly the ultimate all-around wetsuit combining the features of a top end suit at an economical price. Whether you're getting into surfing or out there every weekend, this suit has you covered with its E5 neoprene and E5 Flash Lining, plus the entire suit is glued and blindstitched with seam taping for strength.  Warmth, stretch and flexibility at a great price.",
      "price": "259.95 ",
      "sizes": "4,6,8,8T,10,10T,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Rip-Curl-Womens-Dawn-Patrol-Chest-Zip-Wetsuit-WSM9MW---Black.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":47,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-gul-womens-response-32mm-gbs-back-zip-wetsuit-re1232-black-p-39838.html",
      "name": "Womens Response 3/2mm GBS Back Zip Wetsuit",
      "brand": "GUL",
      "sku": "RE1232-C1",
      "description": "The Gul Response range is the perfect combination of value for money and performance. Constructed using GBS seams and X-Flex super stretch panels for comfort with seam free seat construction. Featuring highly durable Powertex4 knees (except shorti styles) to ensure an increased lifespan. The Response wetsuit meets all the requirements for the all-round watersports enthusiast.",
      "price": "130.99 ",
      "sizes": "4,6,6T,8,8T,8/10,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Gul-Womens-Response-GBS-Back-Zip-Wetsuit-Black---Front.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":48,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-mystic-womens-star-32mm-back-zip-wetsuit-210318-night-blue-p-36952.html",
      "name": "Womens Star 3/2mm Back Zip Wetsuit",
      "brand": "Mystic",
      "sku": "210318",
      "description": "We’re starstruck by the new designs of the Star series. Like last year, this wetsuit is engineered with Glued Blind Stitched seams. Of course, the seams have also been enforced with junction tape on the critical points. So, no water will seep in, that's for sure. This fullsuit with back-zip is equipped with Fox Fleece lining on the torso for a warmer core. It also comes with our durable 4-way stretch Hex-tech pads to keep your knees safe. For every condition there's a Star style.",
      "price": "172.64 ",
      "sizes": "S,M,L,XL",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/35000.210318_449_01.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":49,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-gul-womens-response-32mm-gbs-back-zip-wetsuit-re1232-blue-paisley-p-39839.html",
      "name": "Womens Response 3/2mm GBS Back Zip Wetsuit",
      "brand": "GUL",
      "sku": "RE1232-C1",
      "description": "The Gul Response range is the perfect combination of value for money and performance. Constructed using GBS seams and X-Flex super stretch panels for comfort with seam free seat construction. Featuring highly durable Powertex4 knees (except shorti styles) to ensure an increased lifespan. The Response wetsuit meets all the requirements for the all-round watersports enthusiast.",
      "price": "114.99 ",
      "sizes": "6T",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Gul%20Womens%20Response%2032mm%20GBS%20Back%20Zip%20Wetsuit%20RE1232-C1%20-%20Blue%20Paisley%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":50,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-palm-womens-quantum-3mm-neoprene-front-zip-long-john-wetsuit-black-12236-p-23267.html",
      "name": "Womens Quantum 3mm Neoprene Front Zip Long John Wetsuit",
      "brand": "Palm",
      "sku": "12236",
      "description": "Palm's high quality 3mm neoprene longjohn for women‚ with reinforced knees‚ flatlocked seams and a stretch lumbar panel for freedom of movement. Great for a wide range of watersports.",
      "price": "120.24 ",
      "sizes": "S,M,L",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2018%20Palm%20Ladies%20Quantum%203mm%20Neoprene%20Front%20Zip%20Long%20John%20BLACK%2012236.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":51,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-jobe-womens-sofia-32mm-chest-zip-wetsuit-303522007-vintage-teal-p-41283.html",
      "name": "Womens Sofia 3/2mm Chest Zip Wetsuit",
      "brand": "JOBE",
      "sku": "303522007",
      "description": "The Jobe Sofia is a hotseller in our 3/2 wetsuit range due to its great looks, comfortable fit and attractive price point. The Sofia has a feminine fit which is combined with our comfortable full stretch neoprene for freedom of movement. Our comfortable stitch construction is soft on the skin while the kneepads on the outside are made to endure. No wonder, the Sofia fullsuit is the proven peoples champ.",
      "price": "129.51 ",
      "sizes": "M,XL",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/303522007-1.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":52,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-nyord-womens-furno-32mm-gbs-back-zip-wetsuit-fbw32001-black-p-40700.html",
      "name": "Womens Furno 3/2mm GBS Back Zip Wetsuit",
      "brand": "Nyord",
      "sku": "FBW32001",
      "description": "Perfect for you if: You’re a summer surfer who surfs occasionally, or you’re new to surfing.",
      "price": "99.99 ",
      "sizes": "2,4,6,8,10,12,14,16",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Nyord-Womens-Furno-Back-Zip-Wetsuit-NWF32BZ---Black-Front.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":53,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-skins-womens-rewired-32mm-gbs-chest-zip-wetsuit-rw32wcz-raven-black-ocean-blue-p-44272.html",
      "name": "Womens ReWired 3/2mm GBS Chest Zip Wetsuit",
      "brand": "C-Skins",
      "sku": "C-RW32WCZ",
      "description": "The best-selling ReWired now features Halo X2 neoprene throughout the upper body. This new neoprene is made from waste scrap car tyres, oyster shells and plastic bottles, and without solvent-based glues or chemical yarn dying. The new ReWired is a huge leap forward in our journey towards sustainability, with zero loss in performance. With new under-the-hood enhancements in stretch through the body and legs, the ReWired feels better than ever in the water. Halo X2’s thermal lining and Dark Matter Liquid Skin on the body panel keep the heat in, and our industry-beating Iris II closure system gives maximum protection from water entry. All seams are fully taped for durability, and the FutureFit 2 panel design gives forget-it’s-on comfort for long summer sessions.",
      "price": "296.76 ",
      "sizes": "2,4,6,8,10,12",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2023%20C-Skins%20Womens%20ReWired%2032mm%20GBS%20Chest%20Zip%20Wetsuit%20C-RW32WCZ%20-%20Raven%20Black%20%20Ocean%20Blue-%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":54,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-gul-womens-force-3mm-back-zip-wetsuit-gf1306-black-p-37112.html",
      "name": "Womens G-Force 3mm Back Zip Wetsuit",
      "brand": "GUL",
      "sku": "GF1306-B7",
      "description": "The G-Force is an entry level suit designed to get you in the water for the first time. Even with the low price point the G-Force still offers some impressive tech; keep warm with titanium 2 lined neoprene and our flatlock seam construction ensures durability. If you're looking to get started in watersports on a budget then this should be your first piece of kit.",
      "price": "72.99 ",
      "sizes": "4,6,8,8/10,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Gul-Womens-G-Force-3mm-Back-Zip-Steamer-Wetsuit-GF1306-B7---Black.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":55,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-rip-curl-womens-omega-32mm-stitch-back-zip-wetsuit-wsm9tw-slate-rose-p-40431.html",
      "name": "Womens Omega 3/2mm E-Stitch Back Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9TW",
      "description": "Quality wetsuit from the leading brand with essential features at an economical price. The Omega Steamer is for the surfer who is looking for a quality wetsuit from a reputable brand, without breaking the bank.",
      "price": "119.99 ",
      "sizes": "8",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Rip%20Curl%20Womens%20Omega%2032mm%20E-Stitch%20Back%20Zip%20Wetsuit%20WSM9TW%20-%20Slate%20Rose.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":56,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-peak-womens-energy-32mm-flatlock-back-zip-wetsuit-p3626l-coral-p-41306.html",
      "name": "Womens Energy 3/2mm Flatlock Back Zip Wetsuit",
      "brand": "Peak",
      "sku": "P3626L",
      "description": "",
      "price": "70.14 ",
      "sizes": "6",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Peak%20Womens%20Energy%2032mm%20Flatlock%20Back%20Zip%20Wetsuit%20P3626L%20-%20Coral%20front.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":57,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-oneill-womens-ninja-32mm-chest-zip-wetsuit-5472-black-p-40971.html",
      "name": "Womens Ninja 3/2mm Chest Zip Wetsuit",
      "brand": "O'Neill",
      "sku": "5472",
      "description": "The Ninja Series offers high end quality features, exceptional durability and lasting value. Featuring UltraFlex neoprene for freedom of moment, DL FluidFlex Firewall insulation, internal Ultraflex taped seams and water tight double super seal neck closure. Clean style lines and color blocking complete this well balanced, value packed series.",
      "price": "289.95 ",
      "sizes": "4,6,8,8T,10,12",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/5472%20-%20Black%201.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":58,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-billabong-womens-synergy-32mm-flatlock-back-zip-wetsuit-abjw100140-wild-black-p-43643.html",
      "name": "Womens Synergy 3/2mm Flatlock Back Zip Wetsuit",
      "brand": "Billabong",
      "sku": "ABJW100140",
      "description": "The Synergy Series wetsuits deliver lightweight comfort, premium heat, and innovative technology with superior value and durability. Made from partially recycled Superlight Foam neoprene combined reinforced seams, the women’s wetsuit boasts excellent thermal retention. Silicon Stretch interior lining adds incredible strength and heat without adding bulk. Finished with a back zip entry for easy on and off, the 3/2 Synergy Back Zip Full Wetsuit is offers everything you demand from a premium wetsuit, without breaking the bank.",
      "price": "125.95 ",
      "sizes": "4,6,8,10,12",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2023%20Billabong%20Womens%20Synergy%2032mm%20Back%20Zip%20Wetsuit%20ABJW100132%20-%20Wild%20Black%20Main%20New.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":59,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-gul-womens-response-echo-32mm-chest-zip-wetsuit-re1328-black-p-42482.html",
      "name": "Womens Response Echo 3/2mm Chest Zip Wetsuit",
      "brand": "GUL",
      "sku": "RE1328",
      "description": "",
      "price": "111.99 ",
      "sizes": "8,8T,8/10,10",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/RE1328_C1BKBP_1%20main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":60,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-gul-womens-response-32mm-gbs-back-zip-wetsuit-re1232-blue-teal-p-42824.html",
      "name": "Womens Response 3/2mm GBS Back Zip Wetsuit",
      "brand": "GUL",
      "sku": "RE1232-C1",
      "description": "The Gul Response range is the perfect combination of value for money and performance. Constructed using GBS seams and X-Flex super stretch panels for comfort with seam free seat construction. Featuring highly durable Powertex4 knees (except shorti styles) to ensure an increased lifespan. The Response wetsuit meets all the requirements for the all-round watersports enthusiast.",
      "price": "130.99 ",
      "sizes": "4,6,6T,8,8T,8/10,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Gul%20Womens%20Response%2043mm%20Back%20Zip%20Wetsuit%20RE1248-C1%20-%20Blue%20Teal%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":61,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-xcel-womens-axis-32mm-back-zip-wetsuit-wt32axs0-black-p-42849.html",
      "name": "Womens Axis X 3/2mm Back Zip Wetsuit",
      "brand": "Xcel",
      "sku": "WT32AXS0",
      "description": "Axis X = sealed warmth and strength",
      "price": "274.95 ",
      "sizes": "4,6,8,10,12",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Xcel%20Womens%20Axis%20X%2032mm%20Back%20Zip%20Wetsuit%20WT32AXS0%20-%20Black%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":62,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-skins-womens-element-32mm-flatlock-back-zip-wetsuit-el32stw-slate-coral-p-44268.html",
      "name": "Womens Element 3/2mm Flatlock Back Zip Wetsuit",
      "brand": "C-Skins",
      "sku": "C-EL32STW",
      "description": "The Element series is all about combining performance technology with unbeatable value. We utilise our exclusive Xtend neoprene in the shoulder and sleeves for excellent flexibility, a Super Seal Glideskin collar for exceptional comfort and Dura Flex knee pads for unbeatable durability. The Element is the best wetsuit on the market for those discovering the sea.",
      "price": "107.88 ",
      "sizes": "2,4,6,8,10,14S,12,16S,14,18S",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2023%20C-Skins%20Womens%20Element%2032mm%20Back%20Zip%20Wetsuit%20C-EL32STW%20-%20Slate%20%20Coral%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":63,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-roxy-womens-prologue-32mm-back-zip-wetsuit-erjw103074-black-p-36464.html",
      "name": "Womens Prologue 3/2mm Back Zip Wetsuit",
      "brand": "Roxy",
      "sku": "ERJW103074",
      "description": "",
      "price": "119.95 ",
      "sizes": "8",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2021%20Roxy%20Womens%20Prologue%2032mm%20Back%20Zip%20wetsuit%20erjw103074%20Black%20%281%29.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":64,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-magic-marine-womens-racing-3mm-gbs-long-john-mm011022-black-p-41060.html",
      "name": "Womens Racing 3mm GBS Long John",
      "brand": "Magic Marine",
      "sku": "MM011022",
      "description": "80% M-Flex 3mm neoprene Long John developed using our latest material and technology to create our best winter Long John yet. It features a warm Diamond terry lining combined with 80% M-Flex neoprene for maximum stretch and comfort designed to crossover the necessities of flexibility and warmth. Combine with the Racing 3mm Neoprene Top for all over protection from the cold.",
      "price": "226.6 ",
      "sizes": "S,M",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/MM011022_900_01.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":65,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2021-rip-curl-womens-omega-32mm-gbs-back-zip-wetsuit-wsm9lw-green-p-35112.html",
      "name": "Womens Omega 3/2mm GBS Back Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9LW",
      "description": "The Omega incorporates some high-end features including E5 Neoprene and E3 Neoprene at an economical price.",
      "price": "143.99 ",
      "sizes": "4",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Rip-Curl-Womens-Omega-Back-Zip-Wetsuit-WSM9LW---Green.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":66,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-mystic-womens-brand-32mm-flatlock-back-zip-wetsuit-210319-night-blue-p-36954.html",
      "name": "Womens Brand 3/2mm Flatlock Back Zip Wetsuit",
      "brand": "Mystic",
      "sku": "210319",
      "description": "This wetsuit is equipped with a back-zip entry and 4-way stretch kneepads, a key pocket and a lining saver to keep your suit in good shape. It has been stitched using the flatlock method, which means that the panels have been constructed with a slight overlap and a wide stitch has been used to create a very strong connection. This Brand wetsuit is your perfect match for the warmer conditions.",
      "price": "140.26 ",
      "sizes": "XS,S,XL",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/35000.210319_449_01.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":67,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-roxy-womens-rise-collection-32mm-back-zip-gbs-wetsuit-erjw103089-navy-nights-red-plum-garnet-p-38807.html",
      "name": "Womens Rise Collection 3/2mm Back Zip GBS Wetsuit",
      "brand": "Roxy",
      "sku": "ERJW103089",
      "description": "Features:",
      "price": "199.99 ",
      "sizes": "2,4,6,8",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2021%20Roxy%20Womens%20Rise%20Collection%2032mm%20Back%20Zip%20GBS%20Wetsuit%20ERJW103089%20Navy%20Nights%20Red%20Plum%20Garnet_front.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":68,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-skins-womens-solace-32mm-gbs-back-zip-wetsuit-so32wbz-black-bluestone-tropical-saffron-p-44282.html",
      "name": "Womens Solace 3/2mm GBS Back Zip Wetsuit",
      "brand": "C-Skins",
      "sku": "C-SO32WBZ",
      "description": "The Solace has become the firm favourite amongst women who value quality combined with style. The feminine cut flatters while the continually changing artwork panels add a distinctive and exciting feel to the wetsuit. Not only is the Solace a great looking suit, but is also packed with top-end tech such as Xtend neoprene for remarkable flexibility and Glued and Blindstitched seams for a watertight construction.",
      "price": "215.81 ",
      "sizes": "4,6,8,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2023%20C-Skins%20Womens%20Solace%2032mm%20GBS%20Back%20Zip%20Wetsuit%20C-SO32WBZ%20-%20Black%20%20Bluestone%20Tropical%20%20Saffron-%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":69,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-oneill-womens-reactor-32mm-back-zip-wetsuit-5042-black-berry-p-44168.html",
      "name": "Womens Reactor II 3/2mm Back Zip Wetsuit",
      "brand": "O'Neill",
      "sku": "5042",
      "description": "The newly upgraded reactor II is engineered for performance in a value driven package. A perfect combination of stretch and durability. Fresh colors and graphics with style thats built to last.",
      "price": "144.95 ",
      "sizes": "4,8,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/BERRY-5042.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":70,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2021-billabong-womens-launch-32mm-back-zip-gbs-wetsuit-jwfu1bi3-grey-p-37699.html",
      "name": "Womens Launch 3/2mm Back Zip GBS Wetsuit",
      "brand": "Billabong",
      "sku": "JWFU1BI3",
      "description": "Launch your session with this value and quality-minded wetsuit. Get more stretch in your session with the Launch GBS. Glued and blind stitched seams increase the suit's water tightness, keeping you warmer, and allowing for a more flexible wetsuit experience.",
      "price": "111.99 ",
      "sizes": "0,8,10",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Billabong-Womens-Launch-Back-Zip-GBS-Wetsuit-JWFU1BI3---Grey.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":71,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-palm-womens-blaze-3mm-gbs-front-zip-long-john-wetsuit-jet-grey-12231-p-24322.html",
      "name": "Womens Blaze 3mm GBS Front Zip Long John Wetsuit",
      "brand": "Palm",
      "sku": "12231",
      "description": "Palms' premium cold water wetsuit.  Supple, warm and quick drying.  Made from 3mm Neospan - extremely stretchy, non-petroleum based neoprene with a super soft feel.  The plush Quick Dry lining drains and is dry to the touch much faster than conventional wetsuits, making this a joy to put on.  A classic long john design with full length one-way front entry zipper, Supratex reinforced panels and grippy side print.  It's glued and blindstitched with GlideSkin neoprene ankles to seal the suit and keep you comfortable - perfectly home in cold water.",
      "price": "208.11 ",
      "sizes": "XS,S,M,L",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Palm-Blaze-Womens-3mm-GBS-Front-Zip-Long-John-Wetsuit-Jet-Grey-12231.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":72,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-mystic-womens-brand-32mm-long-arm-short-leg-back-zip-wetsuit-21032-night-blue-p-36955.html",
      "name": "Womens Brand 3/2mm Long Arm Short Leg Back Zip Wetsuit",
      "brand": "Mystic",
      "sku": "21032",
      "description": "This wetsuit is equipped with a back-zip entry and 4-way stretch kneepads, a key pocket and a lining saver to keep your suit in good shape. It has been stitched using the flatlock method, which means that the panels have been constructed with a slight overlap and a wide stitch has been used to create a very strong connection. This Brand wetsuit is your perfect match for the warmer conditions.",
      "price": "135.94 ",
      "sizes": "XS,S,M",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/35000.210320_449_01.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":73,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2021-billabong-womens-launch-32mm-back-zip-gbs-wetsuit-043g18-pacific-p-35545.html",
      "name": "Womens Launch 3/2mm Back Zip GBS Wetsuit",
      "brand": "Billabong",
      "sku": "043G18",
      "description": "Launch your session with this value and quality-minded wetsuit. Get more stretch in your session with the Launch GBS. Glued and blind stitched seams increase the suit's water tightness, keeping you warmer, and allowing for a more flexible wetsuit experience.",
      "price": "139.95 ",
      "sizes": "0",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Billabong-Launch-Pacific-A.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":74,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2021-rip-curl-womens-dawn-patrol-32mm-back-zip-wetsuit-wsm9ns-mid-blue-p-36539.html",
      "name": "Womens Dawn Patrol 3/2mm Back Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9NS",
      "description": "The Rip Curl Dawn Patrol Warmth is a brand new addition the range for this season, featuring a full flash dry lining internally to the front of the suit, which provides incredible warmth during those colder sessions! Truly the ultimate all-around wetsuit combining the features of a top end suit at an economical price. Whether you're getting into surfing or out there every weekend, this suit has you covered with its E5 neoprene and E5 Flash Lining, plus the entire suit is glued and blindstitched with seam taping for strength.  Warmth, stretch and flexibility at a great price.",
      "price": "199.99 ",
      "sizes": "4,10,12",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Rip-Curl-Womens-Dawn-Patrol-Back-Zip-Wetsuit-WSM9DS---Mid-Blue.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    
    {
      "id":76,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-oneill-womens-reactor-32mm-back-zip-wetsuit-5042-black-p-34536.html",
      "name": "Womens Reactor II 3/2mm Back Zip Wetsuit",
      "brand": "O'Neill",
      "sku": "5042",
      "description": "The newly upgraded reactor II is engineered for performance in a value driven package. A perfect combination of stretch and durability. Fresh colors and graphics with style thats built to last.",
      "price": "144.95 ",
      "sizes": "4,8,8T,10,12,14,16",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/ONeill%20Womens%20Reactor%20II%2032mm%20Back%20Zip%20Wetsuit%20BLACK%205042.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":77,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-oneill-womens-epic-32mm-gbs-back-zip-wetsuit-4213-black-tradewnd-tearose-p-44115.html",
      "name": "Womens Epic 3/2mm GBS Back Zip Wetsuit",
      "brand": "O'Neill",
      "sku": "4213",
      "description": "The Epic has many of the same great features as our high-end wetsuits, including 100% UltraFlex neoprene, double seal neck closure, LSD (lumbar seamless design) and re-engineered covert blackout zip. Clean graphics and sharp style lines make the Epic the best value in the industry.",
      "price": "219.95 ",
      "sizes": "4,6,8S,8,8T,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/4214_HS9_P_1-2000x2000-75b40bd0-6823-40fc-a9fe-7651d476fa941.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":78,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-rip-curl-womens-bomb-ltd-edition-32mm-zip-free-wetsuit-wsmytg-black-p-34602.html",
      "name": "Womens E-Bomb Ltd Edition 3/2mm Zip Free Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSMYTG",
      "description": "The E7 Limited Edition E-Bomb is the result of a 3 year project with World Champions Tyler Wright, Mick Fanning, Gabriel Medina and the Rip Curl Wetsuit team.",
      "price": "349.95 ",
      "sizes": "6,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Rip-Curl-Womens-E-Bomb-LTD-32GB-ZF-Wetsuit-WSMYTG-Black.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":79,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-oneill-womens-epic-32mm-gbs-back-zip-wetsuit-4213-black-p-34478.html",
      "name": "Womens Epic 3/2mm GBS Back Zip Wetsuit",
      "brand": "O'Neill",
      "sku": "4213",
      "description": "The Epic has many of the same sick features as our high-end wetsuits, including 100% UltraFlex neoprene, double seal neck closure, lumbar seamless design and re-engineered covert blackout zip. Clean graphics and sharp style lines make the Epic the vest value in the industry.",
      "price": "159.95 ",
      "sizes": "4,6S,6,8S,8,8T,10,10T,12,12T,14,16",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2017-ONeill-Ladies-Epic-32mm-BZ-Wetsuit-BLACK-BLACK-4213.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":80,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2023-gul-womens-response-32mm-back-zip-wetsuit-re1232-grey-marbel-p-42830.html",
      "name": "Womens Response 3/2mm Back Zip Wetsuit",
      "brand": "GUL",
      "sku": "RE1232-C1",
      "description": "GUL's best selling wetsuit! The Response range is long lasting, durable and flexible. The perfect combination of value for money and performance. Constructed with glued and blindstitched seams to keep water out and 100% X-Flex super stretch neoprene, giving you ultimate freedom of movement. The Response wetsuit meets all the requirements for the all round watersports enthusiast.",
      "price": "130.99 ",
      "sizes": "4,6,6T,8,8T,8/10,10,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Gul%20Womens%20Response%2043mm%20Back%20Zip%20Wetsuit%20RE1248-C1%20-%20Grey%20Marbel%20Main.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":81,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2021-gul-womens-response-32mm-back-zip-gbs-wetsuit-re1232-indigo-blue-p-37089.html",
      "name": "Womens Response 3/2mm Back Zip GBS Wetsuit",
      "brand": "GUL",
      "sku": "Re1232-B9",
      "description": "The Gul Response range is the perfect combination of value for money and performance. Constructed using GBS seams and X-Flex super stretch panels for comfort with seam free seat construction. Featuring highly durable Powertex4 knees (except shorti styles) to ensure an increased lifespan. The Response wetsuit meets all the requirements for the all-round watersports enthusiast.",
      "price": "109.99 ",
      "sizes": "4",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/Gul-Womens-Response-Back-Zip-GBS-Wetsuit-Re1232-B9---Indigo-Blue.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":82,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-rip-curl-womens-dawn-patrol-32mm-chest-zip-wetsuit-wsm9cs-slate-rose-p-38688.html",
      "name": "Womens Dawn Patrol 3/2mm Chest Zip Wetsuit",
      "brand": "Rip Curl",
      "sku": "WSM9CS",
      "description": "Dawn Patrol is Rip Curl's ultimate all-around wetsuit combining the features of a top end suit at an economical price. Whether you're getting into surfing or out there every weekend, this suit has you covered with its E5 neoprene and E4 Flash Lining, plus the entire suit is glued and blindstitched with seam taping for strength.  Warmth, stretch and flexibility at a great price. \n\nE5 performance neoprene combined with E4 thermo lining give the surfer great function and performance. The entire suit is glued and blindstitched with 3/4 seam taping.",
      "price": "259.99 ",
      "sizes": "4,12,14",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2021%20Rip%20Curl%20Womens%20Dawn%20Patrol%2032mm%20Chest%20Zip%20Wetsuit%20WSM9CS%20-%20Slate%20Rose.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":83,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-roxy-womens-syncro-32mm-back-zip-wetsuit-erjw103087-jet-black-p-41595.html",
      "name": "Womens Syncro 3/2mm Back Zip Wetsuit",
      "brand": "Roxy",
      "sku": "ERJW103087",
      "description": "3/2mm Syncro - Back Zip Wetsuit for Women. Born and bred at the beach, ROXY understands the importance of fun and functional surfwear. That's why we've created this 3/2mm Syncro steamer for women. A printed design cut from engineered StretchFlight 2 neoprene, this lightweight wetsuit offers endless hours of surfing thanks to its innovative WarmFlight® thermal fleece lining and triple GBS seams to keep you warm and keep water out. Rely on the durable Supratex knee pads for added protection.",
      "price": "147.99 ",
      "sizes": "4,6,8,12,14,16",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/2022%20Roxy%20Womens%20Syncro%2043mm%20Back%20Zip%20Wetsuit%20ERJW103085%20-%20Jet%20Black1.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    },
    {
      "id":84,
      "retailer_id": "WO1",
      "url": "https://www.watersportsoutlet.com/2022-oneill-womens-bahia-32mm-back-zip-wetsuit-5292-black-twiggy-tearose-p-40962.html",
      "name": "Womens Bahia 3/2mm Back Zip Wetsuit",
      "brand": "O'Neill",
      "sku": "5292",
      "description": "The O'Neill Bahia is designed for a new generation of athletes that want to bring beauty to the water.",
      "price": "111.99 ",
      "sizes": "10",
      "image": "https://cdn.watersportsoutlet.com/images/1x1/thumbs/5292-HH9-High-Res-2000x2000-7d8a05eb-e62d-48ce-bd1d-e95fb3fd16af.700x700.jpg",
      "style_id": "2",
      "gender": "Womens"
    }
    
  ]);
};
